[tool.poetry]
name = "batterymodelling"
version = "0.1.0"
description = "MMSC Case Study in Modelling :)"
authors = ["Jad", "Nicholas", "Aoibheann", "Zella", "Peter"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
casadi = "3.5.5"
pybamm = "^23.1"
mat4py = "^0.5.0"
pyside6 = "^6.4.2"
networkx = "^3.0"

[tool.poetry.group.dev.dependencies]
invoke = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
style = ["github://MrP01/lint-me-now/nitpick-base-style.toml", "github://MrP01/lint-me-now/nitpick-python-style.toml"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
exclude = [".git", "**/__pycache__"]
